name: Register Jolter release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  register:
    runs-on: ubuntu-latest
    steps:
      - name: Register release with Jolter
        uses: jolterjs/register-release-action@v1
        with:
          registry-url: https://registry.jolter.dev
          plugin-name: "@jolterjs/jolter"
          github-token: ${{ github.token }}
